
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://admin:password@mongodb:27017/prueba-personalSoft?authSource=admin}

server.port=8080
spring.output.ansi.enabled=DETECT

brevo.api.key=${BREVO_API_KEY}
brevo.sender.email=${BREVO_SENDER_EMAIL}
