
spring.data.mongodb.uri=mongodb://admin:password@localhost:27017/prueba-personalSoft?authSource=admin

server.port=8080
spring.output.ansi.enabled=ALWAYS

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
brevo.api.key=${BREVO_API_KEY}
brevo.sender.email=${BREVO_SENDER_EMAIL}
