
spring.mongodb.uri=mongodb://admin:password@localhost:27017/prueba-personalSoft?authSource=admin

server.port=8080
spring.output.ansi.enabled=ALWAYS

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
